server:
  port: 9000


spring:
  datasource:
#    name: druidDataSource
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://www.sicmed.cn:3306/ehis?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: 123456
# redis配置
  redis:
    host: localhost
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000
#    pool:
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 10
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 100
#       # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapping/**/*Mapper.xml
  typeAliasesPackage: com.sicmed.ehis.registration.entity

#logging.level.com.dy.springboot.server.mapper=debug
logging:
  level:
    com.sicmed.ehis.registration.mapper.*: debug